#!/bin/bash
# Request a CSR Template

# Requires:
#   ../client/deviceID		// ./gen-clientkey
#   ../client/token.json	// ./get-token


TOKEN=`jq -r '.registration.token' ../client/token.json`
SUBSCRIBER=1		# Can be 1,2, or 3. See ../../routes/internal.js. 1 == Grandma

declare -a HEADERS=('-H' "content-type: application/json" '-H' "authorization: $TOKEN")

# Create JSON wrapper
echo "{" > ../tmp/subscriber.json
echo "  \"subscriberID\": \"$SUBSCRIBER\"" >> ../tmp/subscriber.json
echo "}" >> ../tmp/subscriber.json

# Submit the CSR
curl -d @../tmp/subscriber.json http://localhost:3010/ca/csrt -v "${HEADERS[@]}" | tee ../client/csrt.json
