#!/bin/bash
# Request a registration token

deviceID=$(<../client/deviceID)
clientID="www.happyclinic.com";

# Create JSON wrapper
echo "{" > ../tmp/token_req.json
echo "  \"clientID\": \"$clientID\"," >> ../tmp/token_req.json
echo "  \"deviceID\": \"$deviceID\"" >> ../tmp/token_req.json
echo "}" >> ../tmp/token_req.json

# Get token
curl -sS -d @../tmp/token_req.json http://localhost:3010/portal/registration-token -v -H "Content-Type: application/json" | tee ../client/token.json
